### ISSUE TITLE
User warning main.ipynb conversion error

### ISSUE THREAD

**Issue by LPerryman** [ONS-OpenData/ONS-LTIM-Passenger-Survey-4.01#3]
UserWarning: IPython parent '/' is not a writable location, using a temp directory.
[NbConvertApp] ERROR | Error while converting 'main.ipynb'

**Comment by ajtucker** [comment]
ONS Scraper issue, should be fixed by GSS-Cogs/gss-utils#2.

**Comment by mikeAdamss** [comment]
fixed by new scraper.
